version: 1
disable_existing_loggers: False

formatters:
  custom:
    format: "%(asctime)s - %(levelname)s - %(client_addr)s - %(message)s"

handlers:
  default:
    class: logging.StreamHandler
    formatter: custom

loggers:
  uvicorn:
    handlers: [default]
    level: INFO
    propagate: False

  uvicorn.access:
    handlers: [default]
    level: INFO
    propagate: False
